# Generated by Django 2.1.2 on 2018-10-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDNCrawler', '0002_auto_20181019_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userid',
            name='visit',
            field=models.IntegerField(default=-1),
        ),
    ]
