# Generated by Django 2.1.2 on 2018-12-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDNCrawler', '0004_auto_20181105_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
