# Generated by Django 2.0.1 on 2019-01-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSDNCrawler', '0006_auto_20181224_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('name', models.CharField(default='', max_length=512)),
                ('fans_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanses_set', to='CSDNCrawler.UserID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
