# Generated by Django 2.0.1 on 2018-10-18 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='article date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('register_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='user register date')),
            ],
        ),
        migrations.CreateModel(
            name='VisualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlerDate', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 16, 3, 4, 127082, tzinfo=utc), verbose_name='data crowler date')),
                ('originality', models.IntegerField(default=-1)),
                ('fans', models.IntegerField(default=-1)),
                ('likes', models.IntegerField(default=-1)),
                ('comments', models.IntegerField(default=-1)),
                ('csdnlevel', models.IntegerField(default=-1)),
                ('visitors', models.IntegerField(default=-1)),
                ('intergration', models.IntegerField(default=-1)),
                ('rank', models.IntegerField(default=-1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSDNCrawler.UserID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSDNCrawler.UserID'),
        ),
    ]
