# Generated by Django 2.0.1 on 2019-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDNCrawler', '0007_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='crawledDate',
            field=models.DateField(auto_now=True, verbose_name='fans crawled date'),
        ),
        migrations.AddField(
            model_name='fans',
            name='current_total_fans_num',
            field=models.IntegerField(default=-1),
        ),
    ]
