# Generated by Django 2.1.5 on 2019-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDNCrawler', '0010_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='None', max_length=512),
        ),
    ]
